# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2149efd7bb3d1b5f62a1f34c1010fd2c4203f581f76ea29bbefce2f5bc559f2174c6c66757f6f8e0586096740ecf6af3212ce94e1e93f6891be41882a319c482

test:
  secret_key_base: 4377422a8735c02cdb82e443dc72965924873ef4646d8820df9baf7e555be385625bd355607924677a3e423ba15badbae6d8fe64115b1d4acb16dbe6c3813ee6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
